#!/bin/bash
sudo chmod u-x ./Question_Creation/CodeChef_FY_FirstContest/Problem/script.sh
sudo chmod u-x ./Question_Creation/CodeChef_FY_FirstContest/HACKATHON/script.sh
sudo chmod u-x ./Question_Creation/CodeChef_FY_FirstContest/script.sh
sudo chmod u-x ./Question_Creation/CodeChef_FY_FirstContest/HACKING_EXAMS/script.sh
sudo chmod u-x ./Question_Creation/CodeFusion_25/Problem/script.sh
sudo chmod u-x ./Question_Creation/CodeFusion_25/Attendint_Events/script.sh
sudo chmod u-x ./Question_Creation/CodeFusion_25/God_Of_Linux/script.sh
sudo chmod u-x ./Question_Creation/CodeFusion_25/script.sh
sudo chmod u-x ./Question_Creation/CodeFusion_25/Preparint_For_Exams/script.sh
sudo chmod u-x ./Question_Creation/CodeFusion_25/Driving_License/script.sh
sudo chmod u-x ./Question_Creation/script.sh
sudo chmod u-x ./Question_Creation/Contest_Template/Problem/script.sh
sudo chmod u-x ./Question_Creation/Contest_Template/script.sh
sudo chmod u-x ./clean.sh
sudo chmod u-x ./Practice/Vlad_and_unfinished_Business.cpp
sudo chmod u-x ./DSA_LaunchPad/Graphs/execute.sh
sudo chmod u-x ./CSES/Graphs/execute.sh
sudo chmod u-x ./protected.sh
sudo chmod u-x ./Dynamic
sudo chmod u-x Programming/shortest_path_on_graph.cpp
sudo chmod u-x ./Dynamic
sudo chmod u-x Programming/shortest_path_on_graph.exe
sudo chmod u-x ./Algorithms/run.sh
sudo chmod u-x ./Algorithms/hashing.cpp
sudo chmod u-x ./.git/hooks/pre-push.sample
sudo chmod u-x ./.git/hooks/push-to-checkout.sample
#!/bin/bash
sudo chmod u-x ./Question_Creation/CodeChef_FY_FirstContest/Problem/script.sh
sudo chmod u-x ./Question_Creation/CodeChef_FY_FirstContest/HACKATHON/script.sh
sudo chmod u-x ./Question_Creation/CodeChef_FY_FirstContest/script.sh
sudo chmod u-x ./Question_Creation/CodeChef_FY_FirstContest/HACKING_EXAMS/script.sh
sudo chmod u-x ./Question_Creation/CodeFusion_25/Problem/script.sh
sudo chmod u-x ./Question_Creation/CodeFusion_25/Attendint_Events/script.sh
sudo chmod u-x ./Question_Creation/CodeFusion_25/God_Of_Linux/script.sh
sudo chmod u-x ./Question_Creation/CodeFusion_25/script.sh
sudo chmod u-x ./Question_Creation/CodeFusion_25/Preparint_For_Exams/script.sh
sudo chmod u-x ./Question_Creation/CodeFusion_25/Driving_License/script.sh
sudo chmod u-x ./Question_Creation/script.sh
sudo chmod u-x ./Question_Creation/Contest_Template/Problem/script.sh
sudo chmod u-x ./Question_Creation/Contest_Template/script.sh
sudo chmod u-x ./clean.sh
sudo chmod u-x ./Practice/Vlad_and_unfinished_Business.cpp
sudo chmod u-x ./restore.sh
sudo chmod u-x ./DSA_LaunchPad/Graphs/execute.sh
sudo chmod u-x ./CSES/Graphs/execute.sh
sudo chmod u-x ./protected.sh
sudo chmod u-x ./Dynamic
sudo chmod u-x Programming/shortest_path_on_graph.cpp
sudo chmod u-x ./Dynamic
sudo chmod u-x Programming/shortest_path_on_graph.exe
sudo chmod u-x ./Algorithms/run.sh
sudo chmod u-x ./Algorithms/hashing.cpp
sudo chmod u-x ./.git/hooks/pre-push.sample
sudo chmod u-x ./.git/hooks/push-to-checkout.sample
